plugins {
    id 'java-library'
}

dependencies {
    implementation project(':core:shared')
    api project(':features:library:library-api')

    implementation 'io.projectreactor:reactor-core'
    implementation 'org.springframework:spring-web'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
