plugins {
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

dependencies {
    implementation project(':core:orchestrator')
    implementation project(':core:shared')
    implementation project(':features:metadata:metadata-api')
    implementation project(':features:ingestion:ingestion-api')
    implementation project(':core:identity:identity-api') // Keeping identity temporarily for AuthResponse model until moved
    implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.2.0'
    
    // Mapping & Lombok
    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
}
