plugins {
    id 'java'
}

group = 'com.ggar.hibiki.core'
version = '0.0.1-SNAPSHOT'

dependencies {
    implementation project(':core:shared')

    implementation project(':core:identity:identity-api')
    implementation project(':core:player:player-api')
    implementation project(':features:devices:devices-api')

    implementation project(':features:ingestion:ingestion-api')
    implementation project(':features:metadata:metadata-api')
    implementation project(':core:catalog:catalog-api')
    implementation project(':features:library:library-api')
    implementation project(':features:social:social-api')
    implementation project(':features:metrics:metrics-api')

    implementation 'org.springframework:spring-context'
    implementation 'io.projectreactor:reactor-core'
    implementation 'org.springframework.security:spring-security-core'

    implementation "org.mapstruct:mapstruct:${rootProject.ext.versions.mapstruct}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.versions.mapstruct}"

}

tasks.named('test') {
    useJUnitPlatform()
}
