plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.3' apply false
    id 'io.spring.dependency-management' version '1.1.7' apply false
    id 'com.diffplug.spotless' version '6.25.0' apply false
}

allprojects {
    group = 'com.ggar.hibiki'
    version = '0.0.1-SNAPSHOT'

    ext {
        versions = [
            lombok: '1.18.44',
            mapstruct: '1.6.3',
            checkstyle: '11.1.0',
            lombokMapstructBinding: '0.2.0'
        ]
    }

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'com.diffplug.spotless'
    apply plugin: 'checkstyle'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    spotless {
        java {
            palantirJavaFormat()
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }

    checkstyle {
        toolVersion = "${rootProject.ext.versions.checkstyle}"
        configFile = rootProject.file("../config/checkstyle/checkstyle.xml")
        showViolations = true
        maxWarnings = 0
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
        }
    }

    dependencies {
        compileOnly 'org.slf4j:slf4j-api'
        compileOnly "org.projectlombok:lombok:${rootProject.ext.versions.lombok}"
        annotationProcessor "org.projectlombok:lombok:${rootProject.ext.versions.lombok}"
    }
}

defaultTasks 'runApi'

task runApi {
    dependsOn ':presentation:rest-api:bootRun'
}
