plugins {
    id 'java'
}

dependencies {
    // Hereda el contrato
    testImplementation project(':testing:contracts')

    // Mockito para mocks
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.assertj:assertj-core'

    // JUnit runner
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}

test {
    useJUnitPlatform()
}
