plugins {
    id 'java'
}

ext {
    mapstructVersion = "1.5.5.Final"
}

dependencies {
    testImplementation project(":core:identity:identity-api")
    testImplementation project(":core:identity:identity-impl")
    testImplementation project(":core:catalog:catalog-api")
    testImplementation project(":core:catalog:catalog-impl")
    testImplementation project(":core:orchestrator")
    testImplementation project(":core:shared")
    testImplementation project(":features:ingestion:ingestion-api")
    testImplementation project(":features:ingestion:ingestion-impl")
    testImplementation project(":features:library:library-api")
    testImplementation project(":features:library:library-impl")
    testImplementation project(":features:metadata:metadata-api")
    testImplementation project(":features:metadata:metadata-impl")
    testImplementation project(":features:search:search-api")
    testImplementation project(":features:search:search-impl")
    testImplementation project(":features:devices:devices-api")
    testImplementation project(":features:devices:devices-impl")
    testImplementation project(":features:entitlements:entitlements-api")
    testImplementation project(":features:entitlements:entitlements-impl")
    testImplementation project(":packages:jwt")
    testImplementation project(":packages:uuid")
    // Hereda el contrato
    testImplementation project(':testing:contracts')

    // Missing transitives for tests
    testImplementation 'org.springframework.data:spring-data-neo4j'
    testImplementation 'org.mapstruct:mapstruct'
    testImplementation 'io.projectreactor:reactor-test'

    // Mockito para mocks
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.assertj:assertj-core'

    // JUnit runner
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation "org.mapstruct:mapstruct:${mapstructVersion}"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    testAnnotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"
}

test {
    useJUnitPlatform()
}
