dependencies {
    implementation project(':features:devices:devices-api')
    implementation project(':core:shared')
    implementation project(':packages:uuid')

    implementation 'org.springframework.data:spring-data-neo4j'
    implementation 'io.projectreactor:reactor-core'

    implementation "org.mapstruct:mapstruct:${rootProject.ext.versions.mapstruct}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.versions.mapstruct}"
}
