plugins {
    id 'java-library'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':core:catalog:catalog-api')
    implementation project(':core:shared')
    implementation project(':packages:uuid')
    implementation project(':packages:musicbrainz')
    implementation project(':packages:acoustid')
    implementation project(':packages:id3v2')

    implementation 'org.springframework.data:spring-data-neo4j'
    implementation 'io.projectreactor:reactor-core'

    implementation "org.mapstruct:mapstruct:${rootProject.ext.versions.mapstruct}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${rootProject.ext.versions.mapstruct}"
    annotationProcessor "org.projectlombok:lombok-mapstruct-binding:${rootProject.ext.versions.lombokMapstructBinding}"
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}
